name: CMake

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker://danger89/cmake:latest

    - name: Clear CMake cache
      run: rm -rf /home/runner/work/ece2400-sec02-2025/ece2400-sec02-2025/build/CMakeCache.txt

    - name: Run CMake
      run: cmake -B /home/runner/work/ece2400-sec02-2025/ece2400-sec02-2025/build -S /home/runner/work/ece2400-sec02-2025/ece2400-sec02-2025 -DCMAKE_BUILD_TYPE=Release

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make

    - name: Test Avg Main
      working-directory: ${{github.workspace}}/build
      run: ./src/avg-main && ./src/avg-main | grep 15

    - name: Test Square Main
      working-directory: ${{github.workspace}}/build
      run: ./src/square-adhoc && ./src/square-adhoc | grep 100